# Generated by Django 4.1.5 on 2023-01-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=50)),
                ('categories', models.ManyToManyField(to='apiv1.categories')),
                ('departments', models.ManyToManyField(to='apiv1.departments')),
                ('locations', models.ManyToManyField(to='apiv1.locations')),
            ],
        ),
        migrations.AddField(
            model_name='departments',
            name='locations',
            field=models.ManyToManyField(to='apiv1.locations'),
        ),
        migrations.AddField(
            model_name='categories',
            name='departments',
            field=models.ManyToManyField(to='apiv1.departments'),
        ),
        migrations.AddField(
            model_name='categories',
            name='locations',
            field=models.ManyToManyField(to='apiv1.locations'),
        ),
    ]
