# Generated by Django 4.1.5 on 2023-01-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_remove_departments_locations_locations_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='locations',
        ),
        migrations.AddField(
            model_name='locations',
            name='categories',
            field=models.ManyToManyField(to='apiv1.categories'),
        ),
    ]
