# Generated by Django 4.1.5 on 2023-01-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0004_departments_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='categories',
        ),
    ]
