# Generated by Django 4.1.5 on 2023-01-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0005_remove_locations_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='subcategories',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='subcategories',
            name='locations',
        ),
        migrations.AddField(
            model_name='categories',
            name='subcategories',
            field=models.ManyToManyField(to='apiv1.subcategories'),
        ),
        migrations.AddField(
            model_name='locations',
            name='categories',
            field=models.ManyToManyField(to='apiv1.categories'),
        ),
    ]
