# Generated by Django 4.1.5 on 2023-01-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0006_remove_subcategories_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='categories',
        ),
    ]
