# Generated by Django 4.1.5 on 2023-01-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0007_remove_locations_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='location_desc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
