# Generated by Django 4.1.5 on 2023-01-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0008_locations_location_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_name', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=50)),
                ('dept_name', models.CharField(max_length=50)),
                ('cat_name', models.CharField(max_length=50)),
                ('subcat_name', models.CharField(max_length=50)),
            ],
        ),
    ]
